### ISSUE TITLE
Serving svelte Cordova App fails

### ISSUE THREAD

**Issue by macsupport** [framework7io/framework7-cli#61]
Using v3.2.0 of Framework CLI, I tried building an iOS Cordova App using svelte. No errors on build (either with Terminal or ui) but when I try to `run start` or `run dev`, I get a blank screen with a console error `TypeError: undefined is not an object (evaluating 'this.$device')`.
Building a Web App works fine and runs on the local server.

**Comment by jakejcheng** [comment]
^ I'm using React and I got the same thing: blank page and the same error. Tried to use v3.1.0 but the CLI wouldn't let me and insist me upgrading to latest first.

**Comment by nolimits4web** [comment]
Should be fixed in F7-CLI 3.2.1

**Comment by jakejcheng** [comment]
I don't think it's fixed yet. Still getting the same error. `TypeError: undefined is not an object (evaluating 'this.state.products.map')` @nolimits4web 
^this is for React btw
